export interface User {
  /**
   * ID of the user. IDs are automatically generated by MongoDB as Mongo ObjectId strings.
   */
  id: string;
  /**
   * Name of the user.
   */
  name: string;
  /**
   * Email of the user.
   */
  email: string;
  /**
   * True if the user is marked as an admin, false otherwise.
   */
  admin: boolean;
}
